-- Record-only: applied to hosted project (ref `ixdsddfxkrkytiitfici`) via Supabase MCP.
--
-- Stage 1a of the Cloud Knowledge Hub work. Everything here is ADDITIVE — no existing
-- column, constraint, policy or function is modified — so the currently-deployed
-- browser bundle keeps working unchanged while this is live.

-- ---------------------------------------------------------------------------
-- Provenance
-- ---------------------------------------------------------------------------
-- Every existing row got here through a conversion, so the default backfills them
-- correctly and no explicit UPDATE is needed.
alter table public.conversions
  add column if not exists source_type text not null default 'conversion'
    check (source_type in ('conversion','upload','note','api','mcp'));

-- ---------------------------------------------------------------------------
-- Ingest metadata
-- ---------------------------------------------------------------------------
alter table public.conversions
  add column if not exists source_path       text,        -- webkitRelativePath from a folder import
  add column if not exists source_created_at timestamptz, -- frontmatter created/date. NEVER converted_at:
                                                          -- converted_at orders History, drives the dashboard
                                                          -- activity chart, and is the vault sort key.
  add column if not exists frontmatter       jsonb,       -- unrecognised frontmatter keys, preserved not dropped
  add column if not exists content_hash      text,        -- sha256 of the normalized body; null = dedup opt-out
  add column if not exists import_batch_id   uuid;        -- groups one folder import so it can be undone

-- Dedup governs ingested docs only: conversions leave content_hash null and a partial
-- index ignores nulls, so this cannot conflict with the existing 211 rows.
create unique index if not exists conversions_user_content_hash_key
  on public.conversions(user_id, content_hash) where content_hash is not null;

-- ---------------------------------------------------------------------------
-- Per-doc summary (generated by a Make scenario; mirrors brief/brief_generated_at)
-- ---------------------------------------------------------------------------
-- summary_status deliberately has NO DEFAULT. `default 'pending'` would mark all 211
-- existing rows pending — including the 171 that are History-only, never added to the
-- vault — and the drainer would then spend LLM operations summarising documents nobody
-- curated. Only in_vault rows are enqueued, at the bottom of this file.
alter table public.conversions
  add column if not exists summary text,
  add column if not exists summary_generated_at timestamptz,
  add column if not exists summary_status text
    check (summary_status is null
           or summary_status in ('pending','running','ready','failed','manual')),
  add column if not exists summary_attempts integer not null default 0,
  add column if not exists summary_claimed_at timestamptz;

-- ---------------------------------------------------------------------------
-- updated_at + version (agent optimistic concurrency)
-- ---------------------------------------------------------------------------
-- Three steps on purpose. Adding `updated_at timestamptz not null default now()` in one
-- statement would stamp all 211 legacy rows as just-modified, poisoning the
-- `updated_since` incremental-sync contract on day one.
alter table public.conversions add column if not exists updated_at timestamptz;
update public.conversions set updated_at = converted_at where updated_at is null;
alter table public.conversions
  alter column updated_at set default now(),
  alter column updated_at set not null;

-- An integer ETag, not a timestamp. timestamptz round-trips lossily through JSON
-- (Postgres microseconds vs JS milliseconds) and a precision mismatch would produce
-- permanent spurious version conflicts that look like a broken tool.
alter table public.conversions add column if not exists version integer not null default 1;

create or replace function public.conversions_before_update()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  new.version    := coalesce(old.version, 0) + 1;
  return new;
end $$;

-- Created AFTER the updated_at backfill above, so the backfill is not overwritten.
drop trigger if exists conversions_touch on public.conversions;
create trigger conversions_touch before update on public.conversions
  for each row execute function public.conversions_before_update();

create index if not exists conversions_user_updated_idx
  on public.conversions(user_id, updated_at desc);

-- ---------------------------------------------------------------------------
-- Enqueue summaries for the existing vault only (40 rows at time of writing)
-- ---------------------------------------------------------------------------
update public.conversions
   set summary_status = 'pending'
 where in_vault and summary is null and summary_status is null;
